from __future__ import annotations

from enum import StrEnum


class SagaStatus(StrEnum):
    RECEIVED = "RECEIVED"
    SYNTHESIZING = "SYNTHESIZING"
    DRAFTED = "DRAFTED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    DISTRIBUTING = "DISTRIBUTING"
    PARTIALLY_DISTRIBUTED = "PARTIALLY_DISTRIBUTED"
    DISTRIBUTED = "DISTRIBUTED"
    FAILED = "FAILED"
